name: Notify Mobility Feed API on Systems Update

on:
  push:
    branches:
      - main
    paths:
      - systems.csv  # Only run if this file changes
  workflow_dispatch:  # Allow manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        id: onepw_secrets
        uses: 1password/load-secrets-action@v2.0.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CREDENTIALS: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/ifkeehu5gzi7wy5ub5qvwkaire/credential"

      - name: Send a notification to the mobility-feed-api
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.CREDENTIALS }}
          repository: MobilityData/mobility-feed-api
          event-type: gbfs-systems-updated
